AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on AWS Lambda

Globals:
  Function:
    Timeout: 10

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: main.handler
      Runtime: python3.10
      Architectures:
        - arm64
      Environment:
        Variables:
          USERS_TABLE_NAME: LeetCodeProgressUsers-1746776519
          PROGRESS_TABLE_NAME: LeetCodeProgressData-1746776519
          CACHE_BUCKET_NAME: leetcode-progress-cache-718795813953-ap-northeast-1
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        AllSubPaths:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
